name: release

on: 
  push:
    tags:
      - 1.*

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

jobs:
  build_package_publish:
    name: "black → test → build → release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: black
        run: |
          make black

      - name: test
        run: |
          make test
          
      - name: build
        run: |
          make version=$GITHUB_REF_NAME build
          
      - name: release
        run: |
          make release token=$PYPI_TOKEN
